// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkxxRzJ99hHz7LecjHKOktDMWbD8H9NUY',
    appId: '1:82765283728:web:83d62a9ba606b01dae7315',
    messagingSenderId: '82765283728',
    projectId: 'fittrackapp-76fe2',
    authDomain: 'fittrackapp-76fe2.firebaseapp.com',
    storageBucket: 'fittrackapp-76fe2.firebasestorage.app',
    measurementId: 'G-23BH3YLM7K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrOH_sOdzIkWKNqwzdAkW-a29Hma45w5A',
    appId: '1:82765283728:android:56ee0d6fd333df06ae7315',
    messagingSenderId: '82765283728',
    projectId: 'fittrackapp-76fe2',
    storageBucket: 'fittrackapp-76fe2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvCD_rRNpbA-9cBeiRErzs5W8-j02cKLE',
    appId: '1:82765283728:ios:eba275c3459adbf9ae7315',
    messagingSenderId: '82765283728',
    projectId: 'fittrackapp-76fe2',
    storageBucket: 'fittrackapp-76fe2.firebasestorage.app',
    iosBundleId: 'com.example.fitTrackApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvCD_rRNpbA-9cBeiRErzs5W8-j02cKLE',
    appId: '1:82765283728:ios:eba275c3459adbf9ae7315',
    messagingSenderId: '82765283728',
    projectId: 'fittrackapp-76fe2',
    storageBucket: 'fittrackapp-76fe2.firebasestorage.app',
    iosBundleId: 'com.example.fitTrackApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkxxRzJ99hHz7LecjHKOktDMWbD8H9NUY',
    appId: '1:82765283728:web:79f0dc156c69895cae7315',
    messagingSenderId: '82765283728',
    projectId: 'fittrackapp-76fe2',
    authDomain: 'fittrackapp-76fe2.firebaseapp.com',
    storageBucket: 'fittrackapp-76fe2.firebasestorage.app',
    measurementId: 'G-97X6423RXR',
  );
}
